//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::authentications::Entity as Authentications;
pub use super::passkeys::Entity as Passkeys;
pub use super::registrations::Entity as Registrations;
